spring:
  :application:
    name: currency-converter

  r2dbc:
    url: r2dbc:h2:mem:///currency_converter_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    initialization-mode: always