spring:
  :application:
    name: currency-converter

  r2dbc:
    url: r2dbc:h2:mem:///currency_converter_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    initialization-mode: always

security:
  jwt:
    secret-key: kbNkRsLhHBmm78G1yu73Tyo4xv+UrcclXC174MDiqvsT73NqwF6aKAlbcdubCTv1sAqh5QnLMmUbry23P/q8N/AmWg5zEq3BYxrQcRH0gPLmNjqHVCEebaTH7fLHiDMP2xaXWS7uADLJw+0Xj/e6JekK9goJPURpRPeZj/5ndFQ15qJo71/+r9x69PDszkmH4UDmbz4gOCUB0CSIP2JYgYjCAKlsf+rPN8pDw4AKH6WXKMDsn4TmFZ2wu5E7GzaBGy06Zk38NsQxUlsCtCwdkim6JAb+X+Nx5wnB5lTVeNNHZR8izpmNk8LOBXFycUa6UaKfotGIDeveTepPXdPLog
    expiration-minutes: 1440